### ISSUE TITLE
Allowing failure does not work

### ISSUE THREAD

**Issue by axelrindle** [andstor/file-existence-action#1]
The following configuration makes the test fail, if I set the parameter `allow_failure` to `true` and the file `storage/logs/laravel.log` does not exist.

```yml
- name: Check for log file existence
  id: check_files
  uses: andstor/file-existence-action@v1
  with:
    files: "storage/logs/laravel.log"
    allow_failure: true
- name: Archive laravel log file
  uses: actions/upload-artifact@v1
  if: steps.check_files.outputs.files_exists == 'true'
  with:
    name: laravel-log
    path: storage/logs/laravel.log
```
