### ISSUE TITLE
Comma Separated List of Directories Isn't Working

### ISSUE THREAD

**Issue by Julian88Tex** [andstor/file-existence-action#109]
```
      - name: Check For Files To Add
        id: check_additions
        uses: andstor/file-existence-action@v1.1.0
        with:
          files: "changed-sources/force-app, changed-sources/custom-metadata"
```

I keep getting log message `These files don't exist: changed-sources/force-app` and then when I check in another action step `if: steps.check_additions.outputs.files_exists == 'true'` value is apparently `false` even though the second directory `changed-sources/custom-metadata` does include files.

Workaround is running action twice and adding an or (`||`): `steps.check_force_additions.outputs.files_exists == 'true' || steps.check_metadata_additions.outputs.files_exists == 'true'`

Says here it should work: https://github.com/andstor/file-existence-action/blob/main/README.md?plain=1#L26
