### ISSUE TITLE
How to search in specific folder?

### ISSUE THREAD

**Issue by tom10271** [andstor/file-existence-action#12]
```
- name: "Check file existence"
  uses: andstor/file-existence-action@v1
  with:
    files: "/full/path/package.json"
```

Like this? `files: "/full/path/package.json"`
