### ISSUE TITLE
Feature Request: any file mode

### ISSUE THREAD

**Issue by cardil** [andstor/file-existence-action#132]
Hi,

I'd like to propose a feature. To add a `any == false` flag to the action. If set to `true`, the action will return true, if any of the listed globs matches, as opposed to the default setting where all files must exist.

This feature will greatly simplify a common case, where we'd like to check the existence of any of the listed files:

```
- id: golang-sources
  uses: andstor/file-existence-action@v2
  with:
    files: go.mod, go.work
    any: true

- name: Build Go sources
  if: ${{ steps.golang-sources.outputs.files_exists == 'true' }}
  run: |
    go build ./...
```
