### ISSUE TITLE
I can't get directory detection to work at all

### ISSUE THREAD

**Issue by juls858** [andstor/file-existence-action#150]
```
  check-runtime:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project_dir }}/
    outputs:
      files_exists: ${{ steps.check-dir.outputs.files_exists }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check file existence
        id: check-dir
        uses: andstor/file-existence-action@v3
        with:
          files: ./runtime/*, ./runtime, runtime/, runtime, runtime/**/*, runtime/environment.yml

      - run: ls -1
```

`Run andstor/file-existence-action@v3`
```
  with:
    files: ./runtime/*, ./runtime, runtime/, runtime, runtime/**/*, runtime/environment.yml
    ignore_case: false
    follow_symbolic_links: true
    fail: false
These files don't exist: ./runtime/*, runtime/**/*, ./runtime, runtime/, runtime, runtime/environment.yml
```
`Run ls -1`
```
environment.yml
infrastructure
requirements-local.txt
runtime
```
