### ISSUE TITLE
Feature:  use Github working directory

### ISSUE THREAD

**Issue by joergi** [andstor/file-existence-action#160]
In GitHub Actions you can use working directory:

[ documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrunworking-directory)

```yml
jobs:
  a-job-name:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apache-beam-dependency-problem
```

but later in the file existence check, I have to rewrite the working directory:

```yml
   - name: "Check file existence linux"
        id: check_files
        uses: andstor/file-existence-action@v3.0.0
        with:
          files: "./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-runners-direct-java-2.53.0.jar"
          fail: true
```

These examples are from [here](https://github.com/joergi/tryouts/blob/e938b484fe7021eaa7f653edaf741d817b0467a6/.github/workflows/apache-beam-dependency-problem.yml)

there should be a possibility to say: use working_dir  yes or no.

I would love to see the example working like this:

```yml
   - name: "Check file existence linux"
        id: check_files
        uses: andstor/file-existence-action@v3.0.0
        with:
          files: "./apache-beam-dependency-problem/build/install/apache-beam-dependency-problem/lib/beam-runners-direct-java-2.53.0.jar"
          fail: true
          working_dir: true
```

Readme.md should look like this:

| Input variable      |Necessity| Description                                                                                                                                      |Default|
|---------------------|----|--------------------------------------------------------------------------------------------------------------------------------------------------|----|
| `files`             |Required| Comma separated string with paths to files and directories to check for existence. Supports [glob paterns](https://github.com/isaacs/node-glob). ||
| `ignore_case`       |Optional| Ignore if a file name has upper or lower cases.                                                                                                  |`true`|
| `follow_symbolic_links` |Optional| Indicates whether to follow symbolic links.                                                                                                      |`true`|
| `fail`              |Optional| Makes the Action fail on missing files.                                                                                                          |`false`|
| `working dir`       |Optional| Uses the github working directory.                                                                                                               |`false`|

I was trying to look if I could implement it myself, but I was missing the skills to do it in TypeScript

this could also maybe closes issue #150
