### ISSUE TITLE
It's usefull but missing `files` with YAML array, better than string separator when having many files to check

### ISSUE THREAD

**Issue by cuongquay** [andstor/file-existence-action#3]
Solution: accept bot string separator and string array for 
```YAML
with:
  files:
  - package.json
  - README.md
  ...
```
