### ISSUE TITLE
Unable to check existence using glob

### ISSUE THREAD

**Issue by Fleuv** [andstor/file-existence-action#4]
Unable to check for files existence using the glob character (`*`).

# Steps to reproduce
Use the following job in your github workflow.
```
...

jobs:
  my_job_id:
    runs-on: ubuntu-latest
    steps:
      - name: Add foo package
        run: mkdir -p package/foo/ && touch package/foo/package.json
      - name: Add bar package
        run: mkdir -p package/bar/ && touch package/bar/package.json
      - name: Check if files exist
        uses: andstor/file-existence-action@v1
        id: check_files
        with:
          files: "packages/*/package.json"
      - name: Result
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo "Files exist"
```

Expected output:
```
Files exist
```

Actual output:
```
These files doesn't exist: packages/*/package.json
```
